# Generated by Django 5.1.1 on 2024-09-25 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BolsistasValidados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolsistas_id', models.CharField(max_length=22)),
                ('classificacao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DadosBancarios',
            fields=[
                ('dados_bancarios_id', models.AutoField(primary_key=True, serialize=False)),
                ('pis_pasep', models.CharField(max_length=10)),
                ('banco', models.CharField(max_length=200)),
                ('conta', models.CharField(max_length=200)),
                ('dig_v', models.CharField(max_length=20)),
                ('tipo_conta', models.CharField(max_length=20)),
                ('matricula', models.CharField(max_length=200)),
                ('tipo_matricula', models.CharField(max_length=200)),
                ('cpf_avaliador', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Editais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edital_id', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('acao', models.CharField(max_length=200)),
                ('programa', models.CharField(max_length=200)),
                ('ano', models.DateField()),
                ('inicio_vigencia', models.DateField()),
                ('termino_vigencia', models.DateField()),
                ('prazo_bolsa', models.DurationField()),
                ('status_vigencia', models.CharField(choices=[('A', 'Ativo'), ('P', 'Pendente')], max_length=1)),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encargo', models.CharField(max_length=200)),
                ('acao', models.CharField(max_length=200)),
                ('inep', models.CharField(max_length=200)),
                ('email_inst', models.EmailField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('n_endereco', models.IntegerField()),
                ('bairro', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=8)),
                ('escolaridade', models.CharField(choices=[('Superior', 'Superior'), ('Especialização', 'Especialização'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('nome', models.CharField(max_length=200)),
                ('organo_emissor', models.CharField(max_length=200)),
                ('data_emissao', models.DateField()),
                ('data_nasc', models.DateField()),
                ('nome_mae', models.CharField(max_length=200)),
                ('tel1', models.CharField(max_length=13)),
                ('tel2', models.CharField(blank=True, max_length=13, null=True)),
                ('email1', models.EmailField(max_length=200)),
                ('email2', models.EmailField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BolsistasAtivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('bolsistas_validados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco_dados.bolsistasvalidados')),
                ('dados_bancarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco_dados.dadosbancarios')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaPag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pag', models.CharField(choices=[('A', 'Ativo'), ('P', 'Pendente')], max_length=1)),
                ('mes', models.DateField()),
                ('etapas', models.CharField(max_length=200)),
                ('processo', models.CharField(max_length=200)),
                ('bolsistas_ativos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco_dados.bolsistasativos')),
                ('bolsistas_validados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco_dados.bolsistasvalidados')),
            ],
        ),
        migrations.CreateModel(
            name='Convocacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('bolsistas_validados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco_dados.bolsistasvalidados')),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco_dados.editais')),
            ],
        ),
        migrations.AddField(
            model_name='bolsistasvalidados',
            name='edital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco_dados.editais'),
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField()),
                ('ano', models.DateField()),
                ('carga_horaria', models.CharField(max_length=200)),
                ('arquivo_freq', models.FileField(upload_to='frequencias/')),
                ('bolsistas_ativos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco_dados.bolsistasativos')),
                ('bolsistas_validados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco_dados.bolsistasvalidados')),
            ],
        ),
        migrations.CreateModel(
            name='Posse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decla_anuencia', models.URLField()),
                ('termo_disponibilidade', models.URLField()),
                ('termo_compromisso', models.URLField()),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco_dados.editais')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco_dados.usuarios')),
            ],
        ),
    ]
